url: https://raceconditionrunning.com

permalink: /:title/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: kramdown
kramdown:
  entity_output: symbolic
  auto_ids: False
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge

exclude:
  - Makefile
  - "README.md"
  - Gemfile
  - Gemfile.lock
  - posters
  - requirements.txt

sass:
  style: :compressed

liquid:
  error_mode: strict

collections:
  brunch-reviews:
    output: true
