- id: salmon-bay-fremont
  name: "Salmon Bay - Fremont Loop"
  dist: 6.30
  map: "https://www.gmap-pedometer.com/?r=7176070"

- id: seward-loop
  name: "Seward Park Loop"
  dist: 2.40
  map: "http://www.gmap-pedometer.com/?r=6862844"

- id: ob-madison-interlaken
  name: "OB: Madison - Interlaken Park"
  dist: 3.85
  map: "http://www.gmap-pedometer.com/?r=6957914"

- id: discovery-park-loop
  name: "Discovery Park Loop"
  dist: 4.00
  map: "http://www.gmap-pedometer.com/?r=6706949"

- id: ob-discovery-golden-gardens
  name: "OB: Discovery - Golden Gardens"
  dist: 7.43
  map: "https://www.gmap-pedometer.com/?r=7176440"

- id: discovery-magnolia-loop
  name: "Discovery - Magnolia Loop"
  dist: 7.34
  map: "https://www.gmap-pedometer.com/?r=7176422"

- id: ob-madrona-park-sailing-club
  name: "OB: Madrona Park - Sailing Club"
  dist: 6.00
  map: "http://www.gmap-pedometer.com/?r=6957722"

- id: ob-magnolia-blvd-bridge
  name: "OB: Magnolia Blvd - Magnolia Bridge"
  dist: 7.13
  map: "http://www.gmap-pedometer.com/?r=7001208"

- id: ob-madison-mt-baker-beach
  name: "OB: Madison - Mt. Baker Beach"
  dist: 7.19
  map: "http://www.gmap-pedometer.com/?r=6957912"

- id: ob-miller-park-mercer-island
  name: "OB: Miller Park - Mercer Island"
  dist: 10.00
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92019+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=16110&f=9868dd9a5d&n=1&dm=1&context=share&r2=iXrY9xamgNN1r43h21t11R0b43Z30r50f51d11l21V0b11V0b21h77l77n81z613171B3j65F1D0x60fA5d10nB4X51b50Z21r31D10k1J4Lq1LGFMPo1h1g10Y1L0N0d21~10x20~120k30o12g5jA27155J5v20l1054Z10Z313Kn11B2l22H5Z10b20N538LSROv2EJ1H7f18B4Z10D49Oh15X1AFB97d2A985E1a20E5MBGP07274J2l1T33BDd1S9m27w1Da1La15ANSD8f22080C0Q060i10E0c32i23s1Ny1Vi114Py1Ha25i24y1g1c3c1m1CG6G0U181K1U081Y24UAa1Y1g2Gi14S0I1W17S5O3U0a4K2C040040I0690BW170020y208TW11C0M0G1i21s23W1080e60e20g3My80Y14UEIQ081G1E180AA8A4K1E5MFGJKBA9ELY13E381m23Y21o25o41I3Y8Pge19_EBgIt1mj2BYF5gP6y2Iu3IW2Cy1a1u2i1Y348MY2Om26m11y19a2Rw1Hu11S9e29i20C3M00004X1Ah2Ad22RIt1Sv1AZ22x15l1Nl2LX2l1f3Z1t2Bx1H~1Ht35x22~44fKa2ny2q1~m22b1Cv92x18LMX1ADC9a1Z16H032D3J799970D2F272P0DH3RLvA0t40d50V074V4X50F0L2BUV070x20180CVA0050H0330B0J10Z44T6N8R2V0H3RFh1X1f29Z13T2X2072T2J270T5Fn1~1f1b33x12d14Z1IZ2Qx123W1h1Ox14r11h20p30h1050P0B07g21E7OR69MZ1EZ18v14V6l1e1RGIm1UK18381Q0CF6L0D2Z26DA7e29A8GCY19i16ANE3a10s1BI8K2W13w19SNMR47O6c20a10I6m21C1o124Ja32a1063g40K66682W91k101x60j3W21y20W20e22O0M00X1i1f1Qn1GLMFMp1K30j1a440U0Ta22c50Y52oB3oB6y60E0G2k66C48242_62o82m78w24o44c22W10c12W10u34g52s50a30c44q22i22s44A2I0Q0"

- id: ob-miller-park-interlaken
  name: "OB: Miller Park - Interlaken"
  dist: 3.07
  map: "http://www.gmap-pedometer.com/?r=7218014"

- id: pp-discovery-alki
  name: "PP: Discovery Park to Alki Beach"
  dist: 13.54
  map: "http://www.gmap-pedometer.com/?r=6875370"

- id: ob-madison-seward
  name: "OB: Madison - Seward Park"
  dist: 13.82
  map: "http://www.gmap-pedometer.com/?r=7177215"

- id: magnuson-park-loop
  name: "Magnuson Park Loop"
  dist: 2.46
  map: "http://www.gmap-pedometer.com/?r=7177173"

- id: ob-madrona-madison-park
  name: "OB: Madrona - Madison Park"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=7177224"

- id: ob-washington-park-sailing-club
  name: "OB: Washington Park - Sailing Club"
  dist: 10.06
  map: "http://www.gmap-pedometer.com/?r=7189884"

- id: ob-overlake-lake-hill
  name: "OB: Overlake - Lake Hills Park"
  dist: 11.25
  map: "https://www.gmap-pedometer.com/?r=7218048"

- id: lake-washington-loop
  name: "Lake Washington Loop"
  dist: 19.01
  map: "https://www.gmap-pedometer.com/?r=7218074"

- id: ob-colman-seward
  name: "OB: Colman Park - Seward Park"
  dist: 9.63
  map: "https://www.gmap-pedometer.com/?r=7298432"

- id: cap-hill-station-i90-ob
  name: "Capitol Hill Station - I90 Bridge OB"
  dist: 10.7
  map: "https://onthegomap.com/s/a02ohof6"

- id: beacon-lwb-seward-columbia
  name: "Beacon Hill Station - LWB - Seward Park - Columbia City"
  dist: 10.7
  map: "https://onthegomap.com/s/oev39cnv"

- id: beacon-chief-sealth-ob
  name: "Beacon Hill Station, Chief Sealth OB"
  dist: 7.6
  map: "https://onthegomap.com/s/393e6oir"

- id: beacon-mt-sound-ob
  name: "Beacon Hill Station, Mt to Sound OB"
  dist: 4.2
  map: "https://onthegomap.com/s/1fd0jvte"

- id: ob-arboretum-lwb-colman
  name: "OB: Arboretum, LWB, Colman"
  dist: 6.9
  map: "https://onthegomap.com/s/0viljrvr"
