- id: ob-madison-interlaken
  name: "OB: Madison - Interlaken Park"
  dist: 3.85
  map: "http://www.gmap-pedometer.com/?r=6957914"

- id: ob-madrona-park-sailing-club
  name: "OB: Madrona Park - Sailing Club"
  dist: 6.00
  map: "http://www.gmap-pedometer.com/?r=6957722"

- id: ob-madison-mt-baker-beach
  name: "OB: Madison - Mt. Baker Beach"
  dist: 7.19
  map: "http://www.gmap-pedometer.com/?r=6957912"

- id: ob-miller-park-interlaken
  name: "OB: Miller Park - Interlaken"
  dist: 3.07
  map: "http://www.gmap-pedometer.com/?r=7218014"

- id: ob-madison-seward
  name: "OB: Madison - Seward Park"
  dist: 13.82
  map: "http://www.gmap-pedometer.com/?r=7177215"

- id: ob-madrona-madison-park
  name: "OB: Madrona - Madison Park"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=7177224"

- id: ob-washington-park-sailing-club
  name: "OB: Washington Park - Sailing Club"
  dist: 10.06
  map: "http://www.gmap-pedometer.com/?r=7189884"

- id: ob-colman-seward
  name: "OB: Colman Park - Seward Park"
  dist: 9.63
  map: "https://www.gmap-pedometer.com/?r=7298432"

- id: ob-arboretum-lwb-colman
  name: "OB: Arboretum, LWB, Colman"
  dist: 6.9
  map: "https://onthegomap.com/s/0viljrvr"
