- id: ob-madrona-park-sailing-club
  name: "OB: Madrona Park - Sailing Club"
  dist: 6.00
  map: "http://www.gmap-pedometer.com/?r=6957722"

- id: ob-madrona-madison-park
  name: "OB: Madrona - Madison Park"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=7177224"

- id: ob-washington-park-sailing-club
  name: "OB: Washington Park - Sailing Club"
  dist: 10.06
  map: "http://www.gmap-pedometer.com/?r=7189884"

- id: ob-colman-seward
  name: "OB: Colman Park - Seward Park"
  dist: 9.63
  map: "https://www.gmap-pedometer.com/?r=7298432"
