- id: salmon-bay-fremont
  name: "Salmon Bay - Fremont Loop"
  dist: 6.30
  map: "https://www.gmap-pedometer.com/?r=7176070"

- id: seward-loop
  name: "Seward Park Loop"
  dist: 2.40
  map: "http://www.gmap-pedometer.com/?r=6862844"

- id: ob-madison-interlaken
  name: "OB: Madison - Interlaken Park"
  dist: 3.85
  map: "http://www.gmap-pedometer.com/?r=6957914"

- id: discovery-park-loop
  name: "Discovery Park Loop"
  dist: 4.00
  map: "http://www.gmap-pedometer.com/?r=6706949"

- id: ob-cse-foster-island
  name: "OB: CSE - Foster Island"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=6849833"
  cseroute: True

- id: ob-cse-arboretum
  name: "OB: CSE - Arboretum"
  dist: 4.04
  map: "http://www.gmap-pedometer.com/?r=7177223"
  cseroute: True

- id: ob-cse-volunteer
  name: "OB: CSE - Volunteer Park"
  dist: 5.19
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92021+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=8353&f=fa3b4de9e9&n=1&dm=1&context=share&r2=afxY9fslgN01QJJ7f2b1r1r1NRRX1Lb113359L7Rt2y1v3q2VMF4F1LDLG3Q9MLQHC32p2w1Bb1Z2m1L994325432B60A1O1S1A7290D0B0B1b50X1H70Z17x4392F2JGBEN67291901030J0h315473B07050x21B2X165433B1713207PA~1g19C3E31789612101616N1LCh2e39ELW1HQD8r2q3RUB6Z18t20B090t31F070h10j20D0B0x32B2B2b2Ql2Qj2Ql2Of50f53l51H0D0j21f10f11j10f31n63P1F0050H0z30p32j3B00r30t10X20t20X12Z40b30H0Z3AX19Z10Z70p30F0P0f32X40f40f40n3t2Z4Hd25j2Al48v30d2A56D1H15B50N1n29h1Dd1BLJNPLp1PVNh1l1DH99HDd2Bd1RNBd17p10H2D4X1KVSRY19M9MFg23k28a1U_2Ec1Ga18M6O4a10g17050F8JKFS3O1A1A2A0C9g11W22ICk1Ee1a1q1DEDS5W12i102J02_31m3BMA8284q31Y40Y40e40e40c41Y40q31e40q30_31s30q3060m3G2k74mB8u22080c3S00OG0Q2o64g32k10g12g10k22E0I0m52g54g50m2Nk2Pm2Pc2PC1C1y31C0E0k20i1080G0u32A0C0u20a17C5STs2p3E7IPMVADi2d3MBO225252021A587424DABW2f1Q9084182C24463k17y226080C08463W424020A0A281O5CDKFQ3w4420a1880Y1Ic50C2C0E0A081Y3Am1Ec3g1i3k14A22A6C642w2m1W1e2o13A1m3s1A63Y13K828n1G~24H25276P0529476LCd14D4F4D45IR6P01Kl2"
  cseroute: True

- id: cse-bryant-loop
  name: "CSE - Bryant Loop"
  dist: 6.19
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92021+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=9969&f=dc0f103ae3&n=1&dm=1&context=share&r2=cfxY9dslgNVY35OHS363E3G3EBe15M381A065Q18aLs6c3Y1w1I_2IY4Oc4Ey24Y43k154040C181s19i6l1_9p3m2Re17Q3W10Q0w3MW22QGGGKKk1q1e1W2i1u2QY24U0o13A2O2K061020A04060K00PI0I0G0Y10a10a21g10m10S0E0U040i10A0K00C0C0Q0k10g10e20y20q31i30m40q60m30q30u30y30s30y31q30w10Y20w30_340W20Y11k10u23i10m21k10u20_10W20O0q20gB5g93G0O0Q0G0u11q10o21k11m20U1Y53e45C0S0S1U0c33e11q43e1160I080I0g11W1020Q0m11G0G0w11Q0k110C0i10E0C2a40i10Q0o40i30k12y60g10u60e40i21u20q30q60_50K0K0g60M06F0f44n44v22v34j24B0j32J0ZBAhBAhB6X56h62v50R0r42l50j21JDJ0R2X140201B01HP63Ah1070Rl1t1f2x3v3B4BBFHDD997Jt8d9BBH3h1f1j2n2n1t15Jh2h2RVDDN7JL77Z2b2AN1B352n41NZ1h23D7JHJVFJF5VVRp1x1j1f2Lh1d1z3F~23b1030432H1B0D4F2J50Fd10f11f43d41d41B0d1050600X4J00~20f3NF9DFF9FDt1p1~1h2n2Th1BNRn4Fv1l2l4FZ1Bj1B~25b21f24p21VDd1052B2b10507p11r2FX3b1t4l2TLHR037Z11v390Z1X1Jt1t1X1~22Lb17D73Mn275576D1F1N2Z1CZ3Ep3GZ32HVB01036ROn44H25276P0529476LCd14D4F4D45IR4Ja1X3"
  cseroute: True

- id: ob-discovery-golden-gardens
  name: "OB: Discovery - Golden Gardens"
  dist: 7.43
  map: "https://www.gmap-pedometer.com/?r=7176440"

- id: discovery-magnolia-loop
  name: "Discovery - Magnolia Loop"
  dist: 7.34
  map: "https://www.gmap-pedometer.com/?r=7176422"

- id: ob-madrona-park-sailing-club
  name: "OB: Madrona Park - Sailing Club"
  dist: 6.00
  map: "http://www.gmap-pedometer.com/?r=6957722"

- id: ob-cse-ravenna-park
  name: "OB: CSE - Ravenna Park"
  dist: 4.12
  map: "http://www.gmap-pedometer.com/?r=7218018"
  cseroute: True

- id: ob-magnolia-blvd-bridge
  name: "OB: Magnolia Blvd - Magnolia Bridge"
  dist: 7.13
  map: "http://www.gmap-pedometer.com/?r=7001208"

- id: ob-madison-mt-baker-beach
  name: "OB: Madison - Mt. Baker Beach"
  dist: 7.19
  map: "http://www.gmap-pedometer.com/?r=6957912"

- id: ob-miller-park-mercer-island
  name: "OB: Miller Park - Mercer Island"
  dist: 10.00
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92019+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=16110&f=9868dd9a5d&n=1&dm=1&context=share&r2=iXrY9xamgNN1r43h21t11R0b43Z30r50f51d11l21V0b11V0b21h77l77n81z613171B3j65F1D0x60fA5d10nB4X51b50Z21r31D10k1J4Lq1LGFMPo1h1g10Y1L0N0d21~10x20~120k30o12g5jA27155J5v20l1054Z10Z313Kn11B2l22H5Z10b20N538LSROv2EJ1H7f18B4Z10D49Oh15X1AFB97d2A985E1a20E5MBGP07274J2l1T33BDd1S9m27w1Da1La15ANSD8f22080C0Q060i10E0c32i23s1Ny1Vi114Py1Ha25i24y1g1c3c1m1CG6G0U181K1U081Y24UAa1Y1g2Gi14S0I1W17S5O3U0a4K2C040040I0690BW170020y208TW11C0M0G1i21s23W1080e60e20g3My80Y14UEIQ081G1E180AA8A4K1E5MFGJKBA9ELY13E381m23Y21o25o41I3Y8Pge19_EBgIt1mj2BYF5gP6y2Iu3IW2Cy1a1u2i1Y348MY2Om26m11y19a2Rw1Hu11S9e29i20C3M00004X1Ah2Ad22RIt1Sv1AZ22x15l1Nl2LX2l1f3Z1t2Bx1H~1Ht35x22~44fKa2ny2q1~m22b1Cv92x18LMX1ADC9a1Z16H032D3J799970D2F272P0DH3RLvA0t40d50V074V4X50F0L2BUV070x20180CVA0050H0330B0J10Z44T6N8R2V0H3RFh1X1f29Z13T2X2072T2J270T5Fn1~1f1b33x12d14Z1IZ2Qx123W1h1Ox14r11h20p30h1050P0B07g21E7OR69MZ1EZ18v14V6l1e1RGIm1UK18381Q0CF6L0D2Z26DA7e29A8GCY19i16ANE3a10s1BI8K2W13w19SNMR47O6c20a10I6m21C1o124Ja32a1063g40K66682W91k101x60j3W21y20W20e22O0M00X1i1f1Qn1GLMFMp1K30j1a440U0Ta22c50Y52oB3oB6y60E0G2k66C48242_62o82m78w24o44c22W10c12W10u34g52s50a30c44q22i22s44A2I0Q0"

- id: ob-miller-park-interlaken
  name: "OB: Miller Park - Interlaken"
  dist: 3.07
  map: "http://www.gmap-pedometer.com/?r=7218014"

- id: pp-discovery-alki
  name: "PP: Discovery Park to Alki Beach"
  dist: 13.54
  map: "http://www.gmap-pedometer.com/?r=6875370"

- id: ob-cse-magnuson-park
  name: "OB: CSE - Magnuson Park"
  dist: 10.07
  map: "http://www.gmap-pedometer.com/?r=7177166"
  cseroute: True

- id: ob-madison-seward
  name: "OB: Madison - Seward Park"
  dist: 13.82
  map: "http://www.gmap-pedometer.com/?r=7177215"

- id: ob-cse-seward
  name: "OB: CSE - Sailing Club"
  dist: 15.01
  map: "http://www.gmap-pedometer.com/?r=7177219"
  cseroute: True

- id: magnuson-park-loop
  name: "Magnuson Park Loop"
  dist: 2.46
  map: "http://www.gmap-pedometer.com/?r=7177173"

- id: ob-cse-520
  name: "OB: CSE - SR 520"
  dist: 8.00
  map: "http://www.gmap-pedometer.com/?r=7177222"
  cseroute: True

- id: ob-madrona-madison-park
  name: "OB: Madrona - Madison Park"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=7177224"

- id: ob-washington-park-sailing-club
  name: "OB: Washington Park - Sailing Club"
  dist: 10.06
  map: "http://www.gmap-pedometer.com/?r=7189884"

- id: ob-cse-burke
  name: "OB: CSE - Burke Northeast"
  dist: 7.13
  map: "http://www.gmap-pedometer.com/?r=7194368"
  cseroute: True

- id: cse-laurelhurst-loop
  name: "CSE - Laurelhurst Loop"
  dist: 6.52
  map: "http://www.gmap-pedometer.com/?r=7202894"
  cseroute: True

- id: cse-arboretum-foster-loop
  name: "CSE - Arboretum - Foster Island Loop"
  dist: 7.35
  map: "https://www.gmap-pedometer.com/?r=7214448"
  cseroute: True

- id: ob-overlake-lake-hill
  name: "OB: Overlake - Lake Hills Park"
  dist: 11.25
  map: "https://www.gmap-pedometer.com/?r=7218048"

- id: lake-washington-loop
  name: "Lake Washington Loop"
  dist: 19.01
  map: "https://www.gmap-pedometer.com/?r=7218074"

- id: ob-colman-seward
  name: "OB: Colman Park - Seward Park"
  dist: 9.63
  map: "https://www.gmap-pedometer.com/?r=7298432"

- id: arb-union
  name: "CSE - Arboretum - Lake Union Loop"
  dist: 10.22
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92021+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=16441&f=dc0f103ae3&n=1&dm=1&context=share&r2=afxY9hslgNQJJ7f2b1r1r1NRRX1Lb113359L7Rt2y1v3q2VMF4F1LDLG3Q9MLQHC32p2w1Bb1Z2m1L9943254F80A1Ob11~23Z31b20x41P0L82UBEN61s21oB0a29Y131VMz12p11MIEI4I5Y13k12u27s1Dk1Jc19O1OJSDIZ2e1B17Z1Rb6Hh2JTD5L4FUPw59e1Z1e2f1w1TQh1OZ16R011z71B1N5150590B5J2VIF2B3LH16BEd1a2d1c1t1k1LW1FAD3VHT5B2F8702i21k40K2Il1CD3PDX1X1RBx12TBv1DL2RFx2Jh1HVDTDX1TFV9d199DHTPTBX16FEB3n10h1IRo1NKNa1l1Kv14h15X1Z1V9X1230X1y1Z1U74NAX1Aj38VCHI7ED6F7X1NT970NCB8h2EZ4Gd185AFQNY1h1e1r1e1d1e1d3g4DOHq1Je2Lu1j1m2X1Ib1k1f1g1VEb14b11j1Ah1KPM7Q04DK3G3155359Fp1001FH7BB22H31930JDLLZ19FLZ1935H705J911J95Vl1t2z3d1z1FN57n1b25BDHd2l3108FCL79OX1SRk35200z22n30r62r60l84z70hA2p30vK2d40Z42z14b20fGd100f62f60n62p60ZD1l60~j1900r30s3A0i511x319I9u56Y20u1SI4Y25S2W2Ge1Im2i264Q88G8B5P5Jn1Z85HHTNLD7L3XE2n111121011B1N73515011V8n3401121020210d21d407272F29013n60X81n10X42JAN211177132F6V6V15676F0h33b3451X1190r62B0L170Ba10G2C081012t5071122k43MB4144G9E760458D24m1Pu5X3K9Y2b15Fc3h221MHm1Ro1d1c1PW2Ri19a13C783k10A684u31C2U0a62u24Q4MI8240G6MAi2MW1Im1EW18k3Ee41c21w43o30u21UBc3Pi1Hy1T43c1JS5i4l2UDc1Pe1f1U9e3z1s2n1MD4363i2l145S0QHg2j1o2X2m1f1k2~1MHMJKHA7MHGDW2p1e1n1CHMj1W2f4g1z2W1p2Qv1Id1e2z4CRQv1u1~38DJKf1s1156d12378NCAJ67W1j1e1p1QNQJI7g13i55s3404700440312CHKLY1X2s51I0a18y1Ak1AQGSGEw1Ce22U0w16IE684C5Uz1qCRq53CBU9Y29e26G3i10AFq3Vo69m1Fq1h1m312l1c3Lc1x2a49O5M0m12C0i32C1q20q33G4Q1e32e19i10w1AS2e37c1022K0A2E4GCW1COIQW3_11Ak3i2s6g4m4c3AAC8_2m2W1W1QUIs1Y5w6MOi3y3w4Y5k1c28Ic1a3Os38i32c30Y34O4I2QOs40CEm2GY2Kk166I6Uk20i11s40W28g32y14k15s11G1i1Hk23Cj1u2f1e2Lk1Ho15I3S5c20a13_50_29S0e41W15_2Di29ODY1Tu1Ty1FUFa1GK68BOBMRw1Tw1X1e2Fc19Qf5aAz1y3Lm1Pc2Lw23KDe27i20i26s14S8c1Ok2Qy1Qn1Cb10NC9KJc1RW1FI7G8A8GICHIJO5M8IKAE38c16s1s1g2c1K8PK02"
  cseroute: true

- id: cse-seward
  name: "PP: CSE to Seward"
  dist: 12.77
  map: "http://www.gmap-pedometer.com/?r=7329974"

- id: west-seattle-loop-18
  name: "West Seattle Loop 18"
  dist: 18.4
  map: "https://www.gmap-pedometer.com/?r=7375664"

- id: west-seattle-loop-15
  name: "West Seattle Loop 15"
  dist: 15.20
  map: "https://www.gmap-pedometer.com/?r=7375666"

- id: sodo-west-seattle-hook-half
  name: "RCR West Seattle Half"
  dist: 13.1
  map: "https://onthegomap.com/s/v8qu7a5s"

- id: cse-woodinville-cafe
  name : "PP: CSE to Woodinville Cafe"
  dist : 16.20
  map : "https://www.gmap-pedometer.com/?r=7376251"

- id: cse-locks-queen-anne-loop
  name : "CSE Locks - Queen Anne Loop"
  dist : 16.93
  map : "https://www.gmap-pedometer.com/?r=7378977"
  cseroute: True

- id: cse-cap-hill-parks-loop
  name: "CSE - Cap Hill Parks Loop"
  dist: 8.20
  map: "https://www.gmap-pedometer.com/?r=7377059"
  cseroute: True

- id: cse-520-kirkland-marymoor
  name: "PP: CSE to Kirkland to Marymoor"
  dist: 18.00
  map: "https://www.gmap-pedometer.com/?r=7382424"

- id: cse-portagebay-lakeunion
  name: "CSE - Portage Bay - Lake Union - U. Bridge"
  dist: 8.41
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92021+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=13537&f=a79cfef96c&n=1&dm=1&context=share&r2=afxY9fslgN01QJJ7f2b1r1r1NRRX1Lb113359L7Rt2y1v3q2VMF4F1LDLG3Q9MLQHC32p2w1Bb1Z2m1L994325432B60A1O1S1A7290D0B0B1b50X1H70Z17Z11t31P4JG10208SA4e10G22lF9d11zCVv1Vv1LLv14l319w22c106FC5G3U0Y12c22w60C0y20g106080e10m30k1B01s2h31t1031H999DPn1v5Hh1Td1p1p1j1Vf1JT1d2A~15JBv1l1f4Z3P9FB7006050X651900F0H2r40~40H2h30R1~1090V8r13f1010296B0J0l258FY3n4c2f3a2d3E705698B210549c1v1e1r1_4Z6_3z4EFA3c40E0E0u20k306060A280c7027A0A040u1n143KFMJc2~1QNe1X143KHc1X14365g1b1ONe5t4W1RSNC985q3f3OLk2d2Y2z11595D731030341ELCH4311t8r6p7v533B799f2v1f1V~2f2j1b112JD59dAx732F771321352x50147030B033n10n505493D435Z20Z4005321070903006r10xB011013090503010B0J0D0F0j6214B1911336d8102715010x1Kr2U32D492H812X5w13114H3917106b5v110013093D31330z3b1L5d2Lb2r2PX157579Bb2x2LP77d5v611JJ771333p1Z2h4r5ALv3b59HF5b1l1LRl7r9LR79LR~2r3TX10N0LB21JHV490X10r10X25h219GA4IAG246D0LY210j1k121b20B2p40z10Z30H0l40h201K9Y2b1814BCBC9O5MJGVA7C9m1Ro1d1c1PW2Ri19a13C783O0G060A684u31C2C0a20o42u24Q4MIC20304G6MAi2MW1Im1EW18k3Ee41c21w43o30u21UBc3Pi1Hq1P8343c1JS5i4l2UDc1Pe1f1U9e3z1s2n1MD4363i2l145S0QHg2j1o2X2m1f1k2~1MHMJKHA7MHGDW2p1QVEHCHMj1W2f4g1z2W1p2Qv1Id1e2z4CROt1w1X48DJKf1s1158h178NC25ELW1j1e1p1QNQJI7g13i55s3404700440312CHKLY1X2s51I0a18y1Ak1AQGSGEw1Ce2240A0E020w16IE684CF_2p1qARq53CBUFk33S6G021K1M0AFq3Vo69m1Fq1j1o3l1c3Lc1x2a49O5M0c10A2C0O0m10E0C0A2C1q20Y30I3G4Q1e32e19i1080G0E080CAS2e37c12M0A2E4GCW1COAE8CW3_11Ak3i2s6g4m4c3AAC8_2m2W1W1QUIs1Y5w6MOi3y3w4Y5k1c28Ic1a3Os38i32c30Y34O4I2QOs40CEm2GY2BC4AGQSu1Cg166026Q0s41U"

- id: cap-hill-station-i90-ob
  name: "Capitol Hill Station - I90 Bridge OB"
  dist: 10.7
  map: "https://onthegomap.com/s/a02ohof6"

- id: beacon-lwb-seward-columbia
  name: "Beacon Hill Station - LWB - Seward Park - Columbia City"
  dist: 10.7
  map: "https://onthegomap.com/s/oev39cnv"

- id: cap-hill-ship-canal-salmon-bay-burke-uw
  name: "Cap Hill around Salmon Bay to UW"
  dist: 9.1
  map: "https://onthegomap.com/s/pcm6o694"

- id: south-industrial-loop-4th-airport
  name: "SODO Station, 4th Ave + Airport Way Industrial Loop"
  dist: 4.5
  map: "https://onthegomap.com/s/n084r9na"

- id: sodo-i90-view
  name: "SODO Station, Mountains to Sound, I90 View OB"
  dist: 6.0
  map: "https://onthegomap.com/s/vdfutgu0"

- id: northgate-shoreline-beach
  name: "Northgate Station, Shoreline Beach OB"
  dist: 12.2
  map: "https://onthegomap.com/s/9f25pcsk"

- id: uw-to-sodo-station-lwb
  name: "P2P: UW to SODO Station via LWB"
  dist: 9.6
  map: "https://onthegomap.com/s/4rgmm89h"

- id: uw-to-pancake-corral
  name: "UW to Chase Pancake Corral, Beaches"
  dist: 10.3
  map: "https://onthegomap.com/s/6pvff027"

- id: roosevelt-magnuson-loop
  name: "Roosevelt Station, Magnuson Loop"
  dist: 8.5
  map: "https://onthegomap.com/s/okme0g3a"

- id: westlake-sculpture-queen-anne
  name: "Westlake Station, Sculpture Park, Queen Anne Loop"
  dist: 7.2
  map: "https://onthegomap.com/s/i7mlk4f4"

- id: westlake-sodo-industrial-p2p
  name: "Westlake Station, SODO, Industrial P2P"
  dist: 4.0
  map: "https://onthegomap.com/s/m8pat8st"

- id: westlake-sculpture-elliot-ob
  name: "Westlake Station, Sculpture Park, Elliot Bay OB"
  dist: 10.2
  map: "https://onthegomap.com/s/sj71l2mu"

- id: beacon-chief-sealth-ob
  name: "Beacon Hill Station, Chief Sealth OB"
  dist: 7.6
  map: "https://onthegomap.com/s/393e6oir"

- id: beacon-mt-sound-ob
  name: "Beacon Hill Station, Mt to Sound OB"
  dist: 4.2
  map: "https://onthegomap.com/s/1fd0jvte"

- id: westlake-queen-anne-loop
  name: "Westlake Station, Queen Anne Loop"
  dist: 7.75
  map: "https://onthegomap.com/s/nlfgct9h"

- id: westlake-alibertos
  name: "Westlake Station, SODO Station P2P"
  dist: 4.7
  map: "https://onthegomap.com/s/sghgkk1c"

- id: roosevelt-big-carkeek-loop
  name: "Roosevelt Station, Big Carkeek Loop"
  dist: 11.4
  map: "https://onthegomap.com/s/de8kdgkq"

- id: uw-bellevue-tc
  name: "UW to Bellevue TC P2P"
  dist: 9.1
  map: "https://onthegomap.com/s/l1ps9lsi"

- id: uw-lake-union-loop
  name: "UW Lake Union Loop"
  dist: 8.1
  map: "https://onthegomap.com/s/kp513k8r"

- id: uw-portage-bay-agua-verde
  name: "UW, Portage Bay, Agua Verde"
  dist: 3.3
  map: "https://onthegomap.com/s/kt5qp6ek"

- id: ob-arboretum-lwb-colman
  name: "OB: Arboretum, LWB, Colman"
  dist: 6.9
  map: "https://onthegomap.com/s/0viljrvr"

- id: ob-westlake-sculpture-park
  name: "OB: Westlake Station, Sculpture Park"
  dist: 5.1
  map: "https://onthegomap.com/s/100kb28d"

- id: caphill-volunteer-westlake
  name: "Cap Hill Station, Volunteer Park, Westlake Station"
  dist: 4.1
  map: "https://onthegomap.com/s/ste3hrss"

- id: northgate-resevoir-roosevelt
  name: "Northgate, Resevoir, Roosevelt"
  dist: 4.0
  map: "https://onthegomap.com/s/rfcnls5a"

- id: ob-northgate-interurban
  name: "OB: Northgate Station, Interurban Trail"
  dist: 7.0
  map: "https://onthegomap.com/s/k5486orc"

- id: cc-genessee-lwb-seward-loop
  name: "Columbia City Station, Genessee Park, Seward Loop"
  dist: 8.0
  map: https://onthegomap.com/s/gvhj6t17

- id: cc-cheasty-rainer-cc-brunch
  name: "Columbia City Station, Cheasty Trail, Rainier Ave"
  dist: 3.1
  map: https://onthegomap.com/s/6fn9ku4o

- id: ob-cc-genesee-lwb
  name: "OB: Columbia City Station, Genessee Park, LWB"
  dist: 6.5
  map: https://onthegomap.com/s/porql59l

- id: cc-sealth-brunch
  name: "Columbia City Station, Chief Sealth Trail, CC Center"
  dist: 3.1
  map: https://onthegomap.com/s/k39l0cjs

- id: sodo-duwamish-trail-1st-loop
  name: "SODO Station, Duwamish Trail, 1st Ave"
  dist: 7.9
  map: https://onthegomap.com/s/93l1akgc
