- id: mercer-island-half
  name: "Mercer Island Half Marathon"
  dist: 13.20
  map: "http://mercerislandhalf.com/wp-content/uploads/2017/03/17-MIRHM-Half-Marathon-Course-Map-4.pdf"

- id: lord-hill-half
  name: "Lord Hill Half Marathon"
  dist: 13.10
  map: "http://www.evergreentrailruns.com/lord-hill-upcoming#half"

- id: dawg-dash-18
  name: "UW Dawg Dash 2018"
  dist: 6.20
  map: "https://www.washington.edu/alumni/dawgdash"

- id: seattle-half-18
  name: "Seattle Half 2018"
  dist: 13.10
  map: "http://www.seattlemarathon.org/amica-insurance-seattle-marathon/"

- id: salmon-bay-fremont
  name: "Salmon Bay, Fremont Loop"
  dist: 6.30
  map: "https://www.gmap-pedometer.com/?r=7176070"

- id: gas-works-salmon-bay
  name: "Gas works, Locks Loop"
  dist: 8.03
  map: "https://www.gmap-pedometer.com/?r=7176073"

- id: seward-loop
  name: "Seward Park Loop"
  dist: 2.40
  map: "http://www.gmap-pedometer.com/?r=6862844"

- id: green-lake-loop
  name: "Green Lake Loop"
  dist: 2.75
  map: "http://www.gmap-pedometer.com/?r=6862852"

- id: dawg-dash-17
  name: "2017 Seattle Dawg Dash 5k/10k"
  dist: 3.20
  map: "http://depts.washington.edu/alumni/blogs/dawgdash/races/seattle/"

- id: portage-bay-loop
  name: "Portage Bay Loop"
  dist: 3.23
  map: "http://www.gmap-pedometer.com/?r=6849824"
  cseroute: True

- id: salmon-bay-loop
  name: "Salmon Bay Loop"
  dist: 3.45
  map: "http://www.gmap-pedometer.com/?r=6849842"

- id: ob-madison-interlaken
  name: "OB: Madison, Interlaken Park"
  dist: 3.85
  map: "http://www.gmap-pedometer.com/?r=6957914"

- id: discovery-park-loop
  name: "Discovery Park Loop"
  dist: 4.00
  map: "http://www.gmap-pedometer.com/?r=7001206"

- id: ob-gas-works-cse
  name: "OB: Gas Works, CSE"
  dist: 4.00
  map: "http://www.gmap-pedometer.com/?r=6957721"
  cseroute: True

- id: ob-cse-foster-island
  name: "OB: CSE, Foster Island"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=6849833"
  cseroute: True

- id: ob-cse-arboretum
  name: "OB: CSE, Arboretum"
  dist: 4.04
  map: "http://www.gmap-pedometer.com/?r=7177223"
  cseroute: True

- id: ob-cse-volunteer
  name: "OB: CSE, Volunteer Park"
  dist: 5.30
  map: "http://www.gmap-pedometer.com/?r=7218025"
  cseroute: True

- id: cse-bryant-loop
  name: "CSE, Bryant loop"
  dist: 6.06
  map: "https://www.gmap-pedometer.com/?r=7218002"
  cseroute: True

- id: ob-sculpture-park
  name: "OB: Olympic Sculpture Park"
  dist: 5.14
  map: "http://www.gmap-pedometer.com/?r=7197236"

- id: sculpture-park-lake-union
  name: "Sculpture Park, Lake Union"
  dist: 8.82
  map: "http://www.gmap-pedometer.com/?r=7218070"

- id: ob-locks-gg
  name: "OB: Locks, Golden Gardens"
  dist: 4.53
  map: "http://www.gmap-pedometer.com/?r=6957881"

- id: ob-locks-discovery
  name: "OB: Locks, Discovery Park"
  dist: 6.21
  map: "http://www.gmap-pedometer.com/?r=7344701"

- id: ob-discovery-gg
  name: "OB: Discovery, Golden Gardens"
  dist: 7.43
  map: "https://www.gmap-pedometer.com/?r=7176440"

- id: discovery-magnolia-loop
  name: "Discovery, Magnolia Loop"
  dist: 7.34
  map: "https://www.gmap-pedometer.com/?r=7176422"

- id: lower-queen-anne-loop
  name: "Lower Queen Anne Loop"
  dist: 5.12
  map: "http://www.gmap-pedometer.com/?r=6957890"

- id: gas-works-fremont-cut-loop
  name: "Gas Works, Fremont Cut Loop"
  dist: 5.51
  map: "http://www.gmap-pedometer.com/?r=6957927"

- id: ob-madrona-park-sailing-club
  name: "OB: Madrona Park, Sailing Club"
  dist: 6.00
  map: "http://www.gmap-pedometer.com/?r=6957722"

- id: ob-green-lake-ravenna
  name: "OB: Green Lake, Ravenna Park"
  dist: 6.12
  map: "http://www.gmap-pedometer.com/?r=6862850"

- id: ob-cse-ravenna
  name: "OB: CSE, Ravenna Park"
  dist: 4.12
  map: "http://www.gmap-pedometer.com/?r=7218018"
  cseroute: True

- id: lake-union-loop
  name: "Lake Union Loop"
  dist: 6.26
  map: "http://www.gmap-pedometer.com/?r=6862845"

- id: ob-gas-works-green-lake-loop
  name: "OB: Gas Works, Green Lake Loop"
  dist: 6.99
  map: "http://www.gmap-pedometer.com/?r=6957923"

- id: ob-green-lake-loop-gasworks
  name: "OB: Green Lake Loop, Gas works"
  dist: 9.84
  map: "http://www.gmap-pedometer.com/?r=7317466"

- id: ob-gas-works-green-lake
  name: "OB: Gas Works, Green Lake"
  dist: 6.00
  map: "https://www.gmap-pedometer.com/?r=7176445"

- id: ob-magnolia-blvd-bridge
  name: "OB: Magnolia Blvd, Magnolia Bridge"
  dist: 7.13
  map: "http://www.gmap-pedometer.com/?r=7001208"

- id: ob-madison-mt-baker-beach
  name: "OB: Madison, Mt. Baker Beach"
  dist: 7.19
  map: "http://www.gmap-pedometer.com/?r=6957912"

- id: ob-miller-park-mercer-island
  name: "OB: Miller Park, Mercer Island"
  dist: 10.00
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+public+use.&c%5B%5D=Route+data+%C2%A92019+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=16110&f=9868dd9a5d&n=1&dm=1&context=share&r2=iXrY9xamgNN1r43h21t11R0b43Z30r50f51d11l21V0b11V0b21h77l77n81z613171B3j65F1D0x60fA5d10nB4X51b50Z21r31D10k1J4Lq1LGFMPo1h1g10Y1L0N0d21~10x20~120k30o12g5jA27155J5v20l1054Z10Z313Kn11B2l22H5Z10b20N538LSROv2EJ1H7f18B4Z10D49Oh15X1AFB97d2A985E1a20E5MBGP07274J2l1T33BDd1S9m27w1Da1La15ANSD8f22080C0Q060i10E0c32i23s1Ny1Vi114Py1Ha25i24y1g1c3c1m1CG6G0U181K1U081Y24UAa1Y1g2Gi14S0I1W17S5O3U0a4K2C040040I0690BW170020y208TW11C0M0G1i21s23W1080e60e20g3My80Y14UEIQ081G1E180AA8A4K1E5MFGJKBA9ELY13E381m23Y21o25o41I3Y8Pge19_EBgIt1mj2BYF5gP6y2Iu3IW2Cy1a1u2i1Y348MY2Om26m11y19a2Rw1Hu11S9e29i20C3M00004X1Ah2Ad22RIt1Sv1AZ22x15l1Nl2LX2l1f3Z1t2Bx1H~1Ht35x22~44fKa2ny2q1~m22b1Cv92x18LMX1ADC9a1Z16H032D3J799970D2F272P0DH3RLvA0t40d50V074V4X50F0L2BUV070x20180CVA0050H0330B0J10Z44T6N8R2V0H3RFh1X1f29Z13T2X2072T2J270T5Fn1~1f1b33x12d14Z1IZ2Qx123W1h1Ox14r11h20p30h1050P0B07g21E7OR69MZ1EZ18v14V6l1e1RGIm1UK18381Q0CF6L0D2Z26DA7e29A8GCY19i16ANE3a10s1BI8K2W13w19SNMR47O6c20a10I6m21C1o124Ja32a1063g40K66682W91k101x60j3W21y20W20e22O0M00X1i1f1Qn1GLMFMp1K30j1a440U0Ta22c50Y52oB3oB6y60E0G2k66C48242_62o82m78w24o44c22W10c12W10u34g52s50a30c44q22i22s44A2I0Q0"

- id: ob-miller-park-interlaken
  name: "OB: Miller Park, Interlaken"
  dist: 3.07
  map: "http://www.gmap-pedometer.com/?r=7218014"

- id: seattle-half-17
  name: "Seattle Half 2017"
  dist: 13.20
  map: "maps/seattle-half-17.png"

- id: pp-discovery-alki
  name: "PP: Discovery Park to Alki Beach"
  dist: 13.54
  map: "http://www.gmap-pedometer.com/?r=6875370"

- id: redmond-reindeer-romp-18
  name: "Redmond Reindeer Romp 2018"
  dist: 13.20
  map: "http://nwtrailruns.com/events/redmond-reindeer-romp/"

- id: ob-cse-magnuson-park
  name: "OB: CSE, Magnuson Park"
  dist: 10.07
  map: "http://www.gmap-pedometer.com/?r=7177166"
  cseroute: True

- id: ob-madison-seward
  name: "OB: Madison, Seward Park"
  dist: 13.82
  map: "http://www.gmap-pedometer.com/?r=7177215"

- id: ob-cse-seward
  name: "OB: CSE, Sailing Club"
  dist: 15.01
  map: "http://www.gmap-pedometer.com/?r=7177219"
  cseroute: True

- id: magnuson-park-loop
  name: "Magnuson Park Loop"
  dist: 2.46
  map: "http://www.gmap-pedometer.com/?r=7177173"

- id: cse-greenlake-union
  name: "CSE, Greenlake, Lake Union Loop"
  dist: 12.47
  map: "https://gmap-pedometer.com/?r=7169234"
  cseroute: True

- id: greenlake-cse
  name: "Greenlake, CSE Loop"
  dist: 8.46
  map: "http://www.gmap-pedometer.com/?r=7332362"
  cseroute: True

- id: gas-works-queen-anne-loop
  name: "Gas Works, Queen Anne Loop"
  dist: 9.06
  map: "http://www.gmap-pedometer.com/?r=7177175"

- id: ob-cse-520
  name: "OB: CSE, SR 520"
  dist: 8.00
  map: "http://www.gmap-pedometer.com/?r=7177222"
  cseroute: True

- id: ob-madrona-madison-park
  name: "OB: Madrona, Madison Park"
  dist: 4.14
  map: "http://www.gmap-pedometer.com/?r=7177224"

- id: magnuson-series
  name: "Magnuson series races"
  dist: 3.10
  map: "http://magnusonseries.org"

- id: ob-washington-park-sailing-club
  name: "OB: Washington Park, Sailing Club"
  dist: 10.06
  map: "http://www.gmap-pedometer.com/?r=7189884"

- id: ob-cse-burke
  name: "OB: Run on Burke"
  dist: 7.13
  map: "http://www.gmap-pedometer.com/?r=7194368"
  cseroute: True

- id: cse-laurelhurst-loop
  name: "CSE, Laurelhurst Loop"
  dist: 6.52
  map: "http://www.gmap-pedometer.com/?r=7202894"
  cseroute: True

- id: spring-eagle
  name: "Spring Eagle Trail Runs"
  dist: 13.10
  map: "http://nwtrailruns.com/events/spring-eagle-trail-run"

- id: lake-relay
  name: "Lake Hills 50k Relay"
  dist: 31.00
  map: "http://nwtrailruns.com/events/lake-hills-50k-relay/"

- id: cse-arboretum-foster-loop
  name: "CSE, Arboretum, Foster Island loop"
  dist: 7.35
  map: "https://www.gmap-pedometer.com/?r=7214448"
  cseroute: True

- id: ob-overlake-lake-hill
  name: "OB: Overlake, Lake Hills Park"
  dist: 11.25
  map: "https://www.gmap-pedometer.com/?r=7218048"

- id: lake-washington-loop
  name: "Lake Washington Loop"
  dist: 19.01
  map: "https://www.gmap-pedometer.com/?r=7218074"

- id: paradise-valley-18
  name: "Paradise Valley 18"
  dist: 13.10
  map: "http://nwtrailruns.com/events/paradise-valley-trail-run/"

- id: ob-colman-seward
  name: "OB: Colman Park, Sewark Park"
  dist: 9.63
  map: "https://www.gmap-pedometer.com/?r=7298432"

- id: viaduct
  name: "Tunnel to Viaduct"
  dist: 5.00
  map: "https://fizzevents.enmotive.com/events/register/tunnel-to-viaduct-8k"

- id: arb-union
  name: "Arboretum Lake Union"
  dist: 10.00
  map: "https://www.gmap-pedometer.com/?r=7330234"

- id: ebey-kettle
  name: "Ebey Kettle"
  dist: 13.10
  map: "http://nwtrailruns.com/events/fort-ebey-kettles-trail-run/"

- id: sammamish
  name: "Lake Sammamish"
  dist: 13.10
  map: "http://lakesammamishhalf.com/"

- id: cse-seward
  name: "PP: CSE Seward"
  dist: 12.77
  map: "http://www.gmap-pedometer.com/?r=7329974"

- id: west-seattle-loop-18
  name: "West Seattle Loop 18"
  dist: 18.4
  map: "https://www.gmap-pedometer.com/?r=7375664"

- id: west-seattle-loop-15
  name: "West Seattle Loop 15"
  dist: 15.20
  map: "https://www.gmap-pedometer.com/?r=7375666"

- id: cse-woodinville-cafe
  name : "PP: CSE Woodinville Cafe"
  dist : 16.20
  map : "https://www.gmap-pedometer.com/?r=7376251"

- id: cse-locks-queen-anne-loop
  name : "CSE Locks Queen Anne Loop"
  dist : 16.93
  map : "https://www.gmap-pedometer.com/?r=7378977"
  cseroute: True

- id: cse-cap-hill-parks-loop
  name: "CSE - Cap Hill Parks Loop"
  dist: 8.20
  map: "https://www.gmap-pedometer.com/?r=7377059"
  cseroute: True

- id: cse-520-kirkland-marymoor
  name: "PP: CSE - Kirkland - Marymoor"
  dist: 18.00
  map: "https://www.gmap-pedometer.com/?r=7382424"

- id: sculpture-park-interbay
  name: "Sculpture Park - Interbay Loop"
  dist: 8.81
  map: "https://onthegomap.com/?m=r&u=mi&w%5B%5D=Routes+may+not+be+suitable+for+walking.&c%5B%5D=Route+data+%C2%A92019+On+The+Go+Map%2C+OpenStreetMap+Contributors&d=14186&f=59c3371cb9&n=1&dm=1&context=share&r2=g~pY9ldvgNj1x1HLBHCP0599Tb1NTHJ9591IRMRW1p1GFg1Z2_1x2m2f3i2p3Un17LY1d1ELKb1Ch1IZ11P4P_2l5ILA5G2i1c1E6O3CBCHCFIX28j12b1Ar1Cj1Qh1e1j1i2b2a1Di1CQ0IBAIe1x1m1j32p10BM~18v16JAHUZ1W1p1m1r1g2~2W1n1g1j2IJ9D5FUd1w3t4e1z1q5r6g1d2W1h2u1v4a2j38f2In1Ux1Iz1Qn16BUMC5UY1K5q1~1QT8EQe1ACC6_15e1Bc1Vk2v2IDQ5G5e1LaCdFGX1Gb1W3d2m2z1OPAD_1h2i3d4q4~5GX18P4N0l37l2Bh1SFm2760a4X1OHq1v1w2j2QHm5Z3q1Bq2181i33K6k1GO0N0j1FJ5h3472p22p1Cl5a3PIv2k2p1w1NIZ4Y150l28RGCi18m20m3OHUv1W1t1u1Py2p3I5Y2j2y1t1y1f1y1Z1a3b1u2Lc12Y20EEm21m41oK1E3A7696Da20e3280Y2140m10y11y53m10a85k10c11WB1E0A00c10G0W60i50W10s5e1060c12w30c50g10Y3e2c1Sa4W3y1i1UMGAa3Y2A8EAOGGACNY1f3s2y1u1k1m2q1E8069308y2c2i1w1_1i3Mk1a1o3Ie2Ge34k12G4E2W13i25w1F_2HW2t1a45E7MJc15Ap1_2t2m4Va2LW1h2W4DUd1Y2n1w2t1s3PY29U7QRq2HW2Jm2d1y59c1Y1GJW3DY2d1s55S7UNk3DY27a13IDe2Fa25W17SNi1f1e3DS7838v1y3Z2k39M3CNm2DW1f8WIDEX2q4B0X21501c50ANW1r1w3FU3I9E968O2Mx2a6l1y1l1m1j1e1HGb1i1JM7Ed1s2Lo1Jo1BSJi1d1w2BOHe1Pw1DW1Hq1Ve29MTW2X1g218Jc1p1a2~BWAZ3W2H19206r2q1NG12B8h5a3Z1EX1c1B8n1W1B474Z4i2R6d1M1252j2c1j1Gd2GX1Eh44f31l56f40X39x6p2B5Z1VL57472l16x75720Mb30F0N073H05030L2B2z16n1GX1MZ1M37HEVQf1O54LI5EFQFC30J6NM3C5C5ANKR293JAr3_1s3z10PL5720V05705l1v20x22d32t33R15z49h77b4R09zAR0R1R7J7d1Lp1n1f1j177VHV9z410l50r2f20x412X41H0d26b1n10d3Z4n2b3LTf1v1x1l2p2l37BFLJNX1h1HPBDLTVd1DHZ1j1FLDFn1Z2p1X2HL9Dp1Z2j1x1"

- id: SNOW
  name: "SNOW"
  dist: 0.00
  map: "SNOW"

- id: TBD
  name: "TBD"
  dist: 0.00
  map: "TBD"
